name: Build and publish to NPM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: 
          - stable
          - unstable

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'

    - name: Setup node environment
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 14

    - name: Get npm cache directory path
      id: npm-cache-dir-path
      run: echo "::set-output name=dir::$(npm config get cache)"

    - name: Cache node_modules
      uses: actions/cache@v2.1.5
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/${{ matrix.version }}/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Get package version
      id: version
      run: echo "::set-output name=number::$(cat package.json | jq '.version')"
      working-directory: ./${{ matrix.version }}

    - name: Install dependencies
      run: npm ci --no-audit
      working-directory: ./${{ matrix.version }}

    - name: Build
      run: npm run build
      working-directory: ./${{ matrix.version }}

    - name: Publish to npm
      run: npm publish --tag ${{ matrix.version }}
      working-directory: ./${{ matrix.version }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Set as latest
      if: ${{ matrix.version == 'stable' }}
      run: npm dist-tag add @jellyfin/client-axios@${{ steps.version.outputs.number }} latest
      working-directory: ./${{ matrix.version }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
